# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_game_controller_auto_ref.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf.ssl_game_controller_common_pb2 as ssl__game__controller__common__pb2
import protobuf.ssl_game_event_2019_pb2 as ssl__game__event__2019__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ssl_game_controller_auto_ref.proto\x12\x0egameController\x1a ssl_game_controller_common.proto\x1a\x19ssl_game_event_2019.proto\"W\n\x13\x41utoRefRegistration\x12\x12\n\nidentifier\x18\x01 \x02(\t\x12,\n\tsignature\x18\x02 \x01(\x0b\x32\x19.gameController.Signature\"~\n\x13\x41utoRefToController\x12,\n\tsignature\x18\x01 \x01(\x0b\x32\x19.gameController.Signature\x12-\n\ngame_event\x18\x02 \x01(\x0b\x32\x19.gameController.GameEventJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05\"Y\n\x13\x43ontrollerToAutoRef\x12;\n\x10\x63ontroller_reply\x18\x01 \x01(\x0b\x32\x1f.gameController.ControllerReplyH\x00\x42\x05\n\x03msg')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_game_controller_auto_ref_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUTOREFREGISTRATION']._serialized_start=115
  _globals['_AUTOREFREGISTRATION']._serialized_end=202
  _globals['_AUTOREFTOCONTROLLER']._serialized_start=204
  _globals['_AUTOREFTOCONTROLLER']._serialized_end=330
  _globals['_CONTROLLERTOAUTOREF']._serialized_start=332
  _globals['_CONTROLLERTOAUTOREF']._serialized_end=421
# @@protoc_insertion_point(module_scope)
