# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_mixed_team.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ssl_mixed_team.proto\x12\x03ssl\")\n\x08TeamPlan\x12\x1d\n\x05plans\x18\x01 \x03(\x0b\x32\x0e.ssl.RobotPlan\"\xc8\x01\n\tRobotPlan\x12\x10\n\x08robot_id\x18\x01 \x02(\r\x12&\n\x04role\x18\x02 \x01(\x0e\x32\x18.ssl.RobotPlan.RobotRole\x12\x1d\n\nnav_target\x18\x03 \x01(\x0b\x32\t.ssl.Pose\x12\"\n\x0bshot_target\x18\x04 \x01(\x0b\x32\r.ssl.Location\">\n\tRobotRole\x12\x0b\n\x07\x44\x65\x66\x61ult\x10\x00\x12\n\n\x06Goalie\x10\x01\x12\x0b\n\x07\x44\x65\x66\x65nse\x10\x02\x12\x0b\n\x07Offense\x10\x03\" \n\x08Location\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\"3\n\x04Pose\x12\x1a\n\x03loc\x18\x01 \x01(\x0b\x32\r.ssl.Location\x12\x0f\n\x07heading\x18\x02 \x01(\x02\x42\x03\xf8\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_mixed_team_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001'
  _globals['_TEAMPLAN']._serialized_start=29
  _globals['_TEAMPLAN']._serialized_end=70
  _globals['_ROBOTPLAN']._serialized_start=73
  _globals['_ROBOTPLAN']._serialized_end=273
  _globals['_ROBOTPLAN_ROBOTROLE']._serialized_start=211
  _globals['_ROBOTPLAN_ROBOTROLE']._serialized_end=273
  _globals['_LOCATION']._serialized_start=275
  _globals['_LOCATION']._serialized_end=307
  _globals['_POSE']._serialized_start=309
  _globals['_POSE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
