# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_simulation_custom_erforce_robot_spec.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.ssl_simulation_custom_erforce_robot_spec.proto\x12\x06sslsim\"Y\n\x10RobotSpecErForce\x12\x14\n\x0cshoot_radius\x18\x01 \x01(\x02\x12\x17\n\x0f\x64ribbler_height\x18\x02 \x01(\x02\x12\x16\n\x0e\x64ribbler_width\x18\x03 \x01(\x02\x42\x38Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_simulation_custom_erforce_robot_spec_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim'
  _globals['_ROBOTSPECERFORCE']._serialized_start=58
  _globals['_ROBOTSPECERFORCE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
