# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_game_controller_common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ssl_game_controller_common.proto\x12\x0egameController\"7\n\x05\x42otId\x12\n\n\x02id\x18\x01 \x01(\x05\x12\"\n\x04team\x18\x02 \x01(\x0e\x32\x14.gameController.Team\" \n\x08Location\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\"\xbf\x02\n\x0f\x43ontrollerReply\x12?\n\x0bstatus_code\x18\x01 \x01(\x0e\x32*.gameController.ControllerReply.StatusCode\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x12\n\nnext_token\x18\x03 \x01(\t\x12\x42\n\x0cverification\x18\x04 \x01(\x0e\x32,.gameController.ControllerReply.Verification\";\n\nStatusCode\x12\x17\n\x13UNKNOWN_STATUS_CODE\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x0c\n\x08REJECTED\x10\x02\"F\n\x0cVerification\x12\x18\n\x14UNKNOWN_VERIFICATION\x10\x00\x12\x0c\n\x08VERIFIED\x10\x01\x12\x0e\n\nUNVERIFIED\x10\x02\",\n\tSignature\x12\r\n\x05token\x18\x01 \x02(\t\x12\x10\n\x08pkcs1v15\x18\x02 \x02(\x0c\"Y\n\x14\x42\x61llSpeedMeasurement\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\x12\n\nball_speed\x18\x02 \x02(\x02\x12\x1a\n\x12initial_ball_speed\x18\x03 \x01(\x02*)\n\x04Team\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06YELLOW\x10\x01\x12\x08\n\x04\x42LUE\x10\x02*1\n\x08\x44ivision\x12\x0f\n\x0b\x44IV_UNKNOWN\x10\x00\x12\t\n\x05\x44IV_A\x10\x01\x12\t\n\x05\x44IV_B\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_game_controller_common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEAM']._serialized_start=602
  _globals['_TEAM']._serialized_end=643
  _globals['_DIVISION']._serialized_start=645
  _globals['_DIVISION']._serialized_end=694
  _globals['_BOTID']._serialized_start=52
  _globals['_BOTID']._serialized_end=107
  _globals['_LOCATION']._serialized_start=109
  _globals['_LOCATION']._serialized_end=141
  _globals['_CONTROLLERREPLY']._serialized_start=144
  _globals['_CONTROLLERREPLY']._serialized_end=463
  _globals['_CONTROLLERREPLY_STATUSCODE']._serialized_start=332
  _globals['_CONTROLLERREPLY_STATUSCODE']._serialized_end=391
  _globals['_CONTROLLERREPLY_VERIFICATION']._serialized_start=393
  _globals['_CONTROLLERREPLY_VERIFICATION']._serialized_end=463
  _globals['_SIGNATURE']._serialized_start=465
  _globals['_SIGNATURE']._serialized_end=509
  _globals['_BALLSPEEDMEASUREMENT']._serialized_start=511
  _globals['_BALLSPEEDMEASUREMENT']._serialized_end=600
# @@protoc_insertion_point(module_scope)
