# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_gc_api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf.ssl_gc_state_pb2 as ssl__gc__state__pb2
import protobuf.ssl_gc_change_pb2 as ssl__gc__change__pb2
import protobuf.ssl_gc_engine_pb2 as ssl__gc__engine__pb2
import protobuf.ssl_gc_engine_config_pb2 as ssl__gc__engine__config__pb2
from google.protobuf import proto.duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ssl_gc_api.proto\x12\x0egameController\x1a\x12ssl_gc_state.proto\x1a\x13ssl_gc_change.proto\x1a\x13ssl_gc_engine.proto\x1a\x1assl_gc_engine_config.proto\x1a\x1egoogle/protobuf/duration.proto\"\xb3\x01\n\x06Output\x12*\n\x0bmatch_state\x18\x01 \x01(\x0b\x32\x15.gameController.State\x12)\n\x08gc_state\x18\x02 \x01(\x0b\x32\x17.gameController.GcState\x12*\n\x08protocol\x18\x03 \x01(\x0b\x32\x18.gameController.Protocol\x12&\n\x06\x63onfig\x18\x04 \x01(\x0b\x32\x16.gameController.Config\"G\n\x08Protocol\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\x08\x12,\n\x05\x65ntry\x18\x02 \x03(\x0b\x32\x1d.gameController.ProtocolEntry\"\xb1\x01\n\rProtocolEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12&\n\x06\x63hange\x18\x02 \x01(\x0b\x32\x16.gameController.Change\x12\x35\n\x12match_time_elapsed\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x35\n\x12stage_time_elapsed\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\"r\n\x05Input\x12&\n\x06\x63hange\x18\x01 \x01(\x0b\x32\x16.gameController.Change\x12\x13\n\x0breset_match\x18\x02 \x01(\x08\x12,\n\x0c\x63onfig_delta\x18\x03 \x01(\x0b\x32\x16.gameController.Config')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_gc_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OUTPUT']._serialized_start=159
  _globals['_OUTPUT']._serialized_end=338
  _globals['_PROTOCOL']._serialized_start=340
  _globals['_PROTOCOL']._serialized_end=411
  _globals['_PROTOCOLENTRY']._serialized_start=414
  _globals['_PROTOCOLENTRY']._serialized_end=591
  _globals['_INPUT']._serialized_start=593
  _globals['_INPUT']._serialized_end=707
# @@protoc_insertion_point(module_scope)
