# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_gc_engine.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf.ssl_game_controller_geometry_pb2 as ssl__game__controller__geometry__pb2
import protobuf.ssl_game_controller_common_pb2 as ssl__game__controller__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ssl_gc_engine.proto\x12\x0egameController\x1a\"ssl_game_controller_geometry.proto\x1a ssl_game_controller_common.proto\"\x98\x04\n\x07GcState\x12:\n\nteam_state\x18\x01 \x03(\x0b\x32&.gameController.GcState.TeamStateEntry\x12\x41\n\x0e\x61uto_ref_state\x18\x02 \x03(\x0b\x32).gameController.GcState.AutoRefStateEntry\x12@\n\rtracker_state\x18\x03 \x03(\x0b\x32).gameController.GcState.TrackerStateEntry\x12\x38\n\x10tracker_state_gc\x18\x04 \x01(\x0b\x32\x1e.gameController.GcStateTracker\x12\x19\n\x11ready_to_continue\x18\x05 \x01(\x08\x1aM\n\x0eTeamStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.gameController.GcStateTeam:\x02\x38\x01\x1aS\n\x11\x41utoRefStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.gameController.GcStateAutoRef:\x02\x38\x01\x1aS\n\x11TrackerStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.gameController.GcStateTracker:\x02\x38\x01\"\x8b\x01\n\x0bGcStateTeam\x12\x11\n\tconnected\x18\x01 \x01(\x08\x12\x1b\n\x13\x63onnection_verified\x18\x02 \x01(\x08\x12 \n\x18remote_control_connected\x18\x03 \x01(\x08\x12*\n\"remote_control_connection_verified\x18\x04 \x01(\x08\"-\n\x0eGcStateAutoRef\x12\x1b\n\x13\x63onnection_verified\x18\x01 \x01(\x08\"~\n\x0eGcStateTracker\x12\x13\n\x0bsource_name\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x04 \x01(\t\x12\"\n\x04\x62\x61ll\x18\x02 \x01(\x0b\x32\x14.gameController.Ball\x12%\n\x06robots\x18\x03 \x03(\x0b\x32\x15.gameController.Robot\"R\n\x04\x42\x61ll\x12$\n\x03pos\x18\x01 \x01(\x0b\x32\x17.gameController.Vector3\x12$\n\x03vel\x18\x02 \x01(\x0b\x32\x17.gameController.Vector3\"P\n\x05Robot\x12!\n\x02id\x18\x01 \x01(\x0b\x32\x15.gameController.BotId\x12$\n\x03pos\x18\x02 \x01(\x0b\x32\x17.gameController.Vector2')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_gc_engine_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GCSTATE_TEAMSTATEENTRY']._options = None
  _globals['_GCSTATE_TEAMSTATEENTRY']._serialized_options = b'8\001'
  _globals['_GCSTATE_AUTOREFSTATEENTRY']._options = None
  _globals['_GCSTATE_AUTOREFSTATEENTRY']._serialized_options = b'8\001'
  _globals['_GCSTATE_TRACKERSTATEENTRY']._options = None
  _globals['_GCSTATE_TRACKERSTATEENTRY']._serialized_options = b'8\001'
  _globals['_GCSTATE']._serialized_start=110
  _globals['_GCSTATE']._serialized_end=646
  _globals['_GCSTATE_TEAMSTATEENTRY']._serialized_start=399
  _globals['_GCSTATE_TEAMSTATEENTRY']._serialized_end=476
  _globals['_GCSTATE_AUTOREFSTATEENTRY']._serialized_start=478
  _globals['_GCSTATE_AUTOREFSTATEENTRY']._serialized_end=561
  _globals['_GCSTATE_TRACKERSTATEENTRY']._serialized_start=563
  _globals['_GCSTATE_TRACKERSTATEENTRY']._serialized_end=646
  _globals['_GCSTATETEAM']._serialized_start=649
  _globals['_GCSTATETEAM']._serialized_end=788
  _globals['_GCSTATEAUTOREF']._serialized_start=790
  _globals['_GCSTATEAUTOREF']._serialized_end=835
  _globals['_GCSTATETRACKER']._serialized_start=837
  _globals['_GCSTATETRACKER']._serialized_end=963
  _globals['_BALL']._serialized_start=965
  _globals['_BALL']._serialized_end=1047
  _globals['_ROBOT']._serialized_start=1049
  _globals['_ROBOT']._serialized_end=1129
# @@protoc_insertion_point(module_scope)
