# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_simulation_control.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf.ssl_game_controller_common_pb2 as ssl__game__controller__common__pb2
import protobuf.ssl_simulation_config_pb2 as ssl__simulation__config__pb2
import protobuf.ssl_simulation_error_pb2 as ssl__simulation__error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cssl_simulation_control.proto\x12\x06sslsim\x1a ssl_game_controller_common.proto\x1a\x1bssl_simulation_config.proto\x1a\x1assl_simulation_error.proto\"\xa1\x01\n\x0cTeleportBall\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\n\n\x02vx\x18\x04 \x01(\x02\x12\n\n\x02vy\x18\x05 \x01(\x02\x12\n\n\x02vz\x18\x06 \x01(\x02\x12\x1e\n\x0fteleport_safely\x18\x07 \x01(\x08:\x05\x66\x61lse\x12\x13\n\x04roll\x18\x08 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08\x62y_force\x18\t \x01(\x08:\x05\x66\x61lse\"\xbd\x01\n\rTeleportRobot\x12!\n\x02id\x18\x01 \x02(\x0b\x32\x15.gameController.BotId\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\x13\n\x0borientation\x18\x04 \x01(\x02\x12\x0e\n\x03v_x\x18\x05 \x01(\x02:\x01\x30\x12\x0e\n\x03v_y\x18\x06 \x01(\x02:\x01\x30\x12\x14\n\tv_angular\x18\x07 \x01(\x02:\x01\x30\x12\x0f\n\x07present\x18\x08 \x01(\x08\x12\x17\n\x08\x62y_force\x18\t \x01(\x08:\x05\x66\x61lse\"\x88\x01\n\x10SimulatorControl\x12+\n\rteleport_ball\x18\x01 \x01(\x0b\x32\x14.sslsim.TeleportBall\x12-\n\x0eteleport_robot\x18\x02 \x03(\x0b\x32\x15.sslsim.TeleportRobot\x12\x18\n\x10simulation_speed\x18\x03 \x01(\x02\"f\n\x10SimulatorCommand\x12)\n\x07\x63ontrol\x18\x01 \x01(\x0b\x32\x18.sslsim.SimulatorControl\x12\'\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x17.sslsim.SimulatorConfig\";\n\x11SimulatorResponse\x12&\n\x06\x65rrors\x18\x01 \x03(\x0b\x32\x16.sslsim.SimulatorErrorB8Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_simulation_control_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim'
  _globals['_TELEPORTBALL']._serialized_start=132
  _globals['_TELEPORTBALL']._serialized_end=293
  _globals['_TELEPORTROBOT']._serialized_start=296
  _globals['_TELEPORTROBOT']._serialized_end=485
  _globals['_SIMULATORCONTROL']._serialized_start=488
  _globals['_SIMULATORCONTROL']._serialized_end=624
  _globals['_SIMULATORCOMMAND']._serialized_start=626
  _globals['_SIMULATORCOMMAND']._serialized_end=728
  _globals['_SIMULATORRESPONSE']._serialized_start=730
  _globals['_SIMULATORRESPONSE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
