# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timeline.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf.logfile_pb2 as logfile__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etimeline.proto\x12\x08timeline\x1a\rlogfile.proto\"C\n\x0b\x46rameLookup\x12\x1e\n\x03uid\x18\x01 \x02(\x0b\x32\x11.logfile.UidEntry\x12\x14\n\x0c\x66rame_number\x18\x02 \x02(\r\"k\n\x0f\x46rameDescriptor\x12\x11\n\tbase_hash\x18\x01 \x02(\t\x12\x19\n\x11\x62\x61se_frame_number\x18\x02 \x02(\r\x12*\n\x0b\x66rame_infos\x18\x03 \x03(\x0b\x32\x15.timeline.FrameLookup\"\x94\x02\n\tGameEvent\x12+\n\x08location\x18\x01 \x02(\x0b\x32\x19.timeline.FrameDescriptor\x12.\n\x08progress\x18\x02 \x02(\x0e\x32\x1c.timeline.GameEvent.Progress\x12\x11\n\trandom_id\x18\x06 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0b\n\x03tag\x18\x04 \x03(\t\x12\x10\n\x08\x61ssignee\x18\x05 \x01(\t\"c\n\x08Progress\x12\x08\n\x04Open\x10\x01\x12\n\n\x06\x43losed\x10\x02\x12\r\n\tPostponed\x10\x03\x12\x0c\n\x08Resolved\x10\x04\x12\x0e\n\nInProgress\x10\x05\x12\x08\n\x04Info\x10\x06\x12\n\n\x06Merged\x10\x07\"\xd7\x01\n\x0cTimelineInit\x12\"\n\x07primary\x18\x01 \x02(\x0b\x32\x11.logfile.UidEntry\x12$\n\tsecondary\x18\x02 \x03(\x0b\x32\x11.logfile.UidEntry\x12$\n\tpartially\x18\x03 \x03(\x0b\x32\x11.logfile.UidEntry\x12.\n\x05state\x18\x04 \x02(\x0e\x32\x1f.timeline.TimelineInit.Resolved\"\'\n\x08Resolved\x12\n\n\x06Solved\x10\x01\x12\x0f\n\x0b\x43onflicting\x10\x02\"E\n\x0c\x45ventWrapper\x12\x0b\n\x03tag\x18\x01 \x02(\t\x12(\n\x0b\x63onflicting\x18\x02 \x03(\x0b\x32\x13.timeline.GameEvent\"n\n\x06Status\x12)\n\x07wrapper\x18\x01 \x01(\x0b\x32\x16.timeline.EventWrapperH\x00\x12)\n\ngame_event\x18\x02 \x01(\x0b\x32\x13.timeline.GameEventH\x00\x42\x0e\n\x0clogfileEntryB\x03\xf8\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timeline_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001'
  _globals['_FRAMELOOKUP']._serialized_start=43
  _globals['_FRAMELOOKUP']._serialized_end=110
  _globals['_FRAMEDESCRIPTOR']._serialized_start=112
  _globals['_FRAMEDESCRIPTOR']._serialized_end=219
  _globals['_GAMEEVENT']._serialized_start=222
  _globals['_GAMEEVENT']._serialized_end=498
  _globals['_GAMEEVENT_PROGRESS']._serialized_start=399
  _globals['_GAMEEVENT_PROGRESS']._serialized_end=498
  _globals['_TIMELINEINIT']._serialized_start=501
  _globals['_TIMELINEINIT']._serialized_end=716
  _globals['_TIMELINEINIT_RESOLVED']._serialized_start=677
  _globals['_TIMELINEINIT_RESOLVED']._serialized_end=716
  _globals['_EVENTWRAPPER']._serialized_start=718
  _globals['_EVENTWRAPPER']._serialized_end=787
  _globals['_STATUS']._serialized_start=789
  _globals['_STATUS']._serialized_end=899
# @@protoc_insertion_point(module_scope)
